### ISSUE TITLE
.ass file support

### ISSUE THREAD

**Issue by Torch3333** [tcrespog/vlc-subtitle-word-search#2]
Hi
The addon does not seem to support .ass file at the moment.
Even though, a subtitle file in associated with the .mkv file, it is not displayed in the loading menu on the extension window.

**Comment by tcrespog** [comment]
Hello, @Torch3333.

The addon only supports external SRT files. If you want to add support to other subtitle formats, feel free to participate.

Regards.

**Comment by Torch3333** [comment]
Hello @tcrespog,

Thank you for the quick answer, I'll try to convert the ASS to a SRT file then. 

Regards
