### ISSUE TITLE
Malformed subtitle number on line 1.

### ISSUE THREAD

**Issue by ajanjairam** [tcrespog/vlc-subtitle-word-search#3]
Whenever i try to use the extension, it shows **Malformed subtitle number on line 1.** in word search area and nothing in subtitles word area

**Comment by tcrespog** [comment]
Hi @ajanjairam.

Please, make sure that the SRT file has a valid [format](https://en.wikipedia.org/wiki/SubRip#File_format) and it's encoded as UTF-8 (not as [UTF-8-BOM](https://en.wikipedia.org/wiki/UTF-8#Byte_order_mark) or any other encoding).

It the file is malformed, you can try repairing the file or searching for another one.
If the file is not encoded as UTF-8, you can convert it using a text editor; for example, Notepad in Windows allows to save the file in UTF-8.

If the error persists, please tell me and we'll see.

**Comment by ajanjairam** [comment]
Mostly the error occurs for the subtitle downloaded using VLsub, I tried converting to UTF-8 and it worked. Please make sure the subtitles downloaded using VLsub works with next update or version. Thanks for replying.

**Comment by tcrespog** [comment]
I'm glad that you solved the problem.
I'll investigate deeper about supporting encodings other than UTF-8 in the (hopefully short) future.

**Comment by tcrespog** [comment]
Release [v1.4 ](https://github.com/tcrespog/vlc-subtitle-word-search/releases/tag/v1.4)now supports UTF-8 BOM files.
