### ISSUE TITLE
Searching embedded subtitles

### ISSUE THREAD

**Issue by Abba-** [tcrespog/vlc-subtitle-word-search#4]
This might be out of scope, but it doesn't seem to be able to pull a subtitle that's embedded with the video file/container (ex mkv).

`No subtitle files found at 'xyz.mkv'

Either way, thanks.  Finding it very useful.
(Another suggestion: If possible to quickly search all the subtitles for a specific word)

**Comment by tcrespog** [comment]
HI @Abba-,

Unfortunately, the plugin can't read subtitles embedded in an MKV video; it only works with external [SRT](https://en.wikipedia.org/wiki/SubRip) subtitle files. However, you could still extract the files from the MKV to an SRT file using software such as [MKVToolNix](https://mkvtoolnix.download/).

Likewise, given that the SRT file is a text file, you could open the file with any text editor so as to search for occurrences of a word among the subtitles.

Glad you're finding the plugin useful. Kind regards.
